[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "shepherd-docs"
authors = [{name = "pli", email = "helene.plisnier@vub.be"}]
dynamic = ["version", "description"]
